travis:
  secure:
    BINSTAR_TOKEN: KFNpx2dIwZjOmdGQ23CuIaO69RgHNtlXkznwZns+ZpL6pD2roe45pKJ/+pqtwgv/poWL1EkjG8FnCG8Qw5xJ+kv6EVMyXRzB63pPSg1jXTxguW2aD3e6AQr8JqokTXX7cu+DATar8R0SCYyol+OAlQQMPpFxwlSWTh/htRz0wYext3ya1HetS2bkzWN2zEHLYi1hcoI4NdxnB/McnNNjlFJY66AZdjtVPAdpnKlTHNBJ5BCEHphot5n8MhSSrypjoXUFpaoq3QTfCyepiWFip5sq4CDY2UQl35fo/UNMQncXU/xtdUKrzNnnvtgJCCwDIGazTWOjtAMpoKovwzZbZjURlkLnxz8ZIvphLCz1WfmmpP7M6DFARpfTCZS81IZMbeejdB6a527G/UfkzNE80+QP2kAh/gDHxF2zhCZ83ALK9+9xBGp5VxY/yO2B+/4xaFNbUlH1LUAAkevTmuSS9bHa2uan2Yw8ECM1+36xru23iszNzyktgCSV5calQQqtBD874GIU6PozahWW4Vtg28hR8Jd+X6JlJr0mlefKpKb8grrVbjintf9Ij1QM09YBxol915fkc0wktD92NdLSzZ6Ic3p0YmnIIHSc85LsfEuwqwtuWnrmeRr54w5hiBcDG9pO9aV8twSMVBUkqdkihJzscNDbTqZrCjaWiEsYWW4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
